version: '3.8'

# HTTPS対応版Docker Compose設定
# セキュリティ強化とHTTPS通信に対応
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"    # HTTP（本番では443へのリダイレクト用）
      - "443:443"  # HTTPS
    depends_on:
      - backend
    volumes:
      # SSL証明書マウント（本番環境では実際の証明書を配置）
      - ./ssl/localhost.crt:/etc/ssl/certs/localhost.crt:ro
      - ./ssl/localhost.key:/etc/ssl/private/localhost.key:ro
    networks:
      - app-network
    restart: unless-stopped
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - GIN_MODE=release
      - DB_HOST=database
      - DB_PORT=3306
      - DB_USER=root
      - DB_NAME=household_budget
      # HTTPSプロキシ対応
      - TRUST_PROXY=true
    secrets:
      - db_password
      - jwt_secret
      - csrf_secret
      - session_secret
    networks:
      - app-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    image: mysql:8.0
    # データベースポートは外部公開しない（セキュリティ強化）
    environment:
      - MYSQL_DATABASE=household_budget
      - TZ=Asia/Tokyo
    secrets:
      - mysql_root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - app-network
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --default-time-zone=+09:00
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

secrets:
  db_password:
    file: ./secrets/db_password.txt
  jwt_secret:
    file: ./secrets/jwt_secret.txt
  csrf_secret:
    file: ./secrets/csrf_secret.txt
  session_secret:
    file: ./secrets/session_secret.txt
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge
